### ISSUE TITLE
Package cannot be authenticated on Ubuntu 14.04

### ISSUE THREAD

**Issue by vincecima** [thoughtbot/rcm#128]
Fresh install of Ubuntu 14.04 and I ran these commands:
1. sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm
2. sudo apt-get install rcm

Last command gives this output:

```
The following NEW packages will be installed:
  rcm
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 18.0 kB of archives.
After this operation, 80.9 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  rcm
Install these packages without verification? [y/N] n
```

Adding the repo appeared to work correctly, not sure why the package cannot be verified.

**Comment by Frost** [comment]
@vincecima It seems like I had made some mistakes when signing the first package, possibly related to the fact that it was a source package and I might have followed a guide for binary packages.

The documentation on packaging in ubuntu is very lengthy, and if you try to search for summaries (which I did, since I am lazy and don't feel like reading an entire book on this), you get a bunch of different ones, so it is not completely obvious exactly what you need to do in each step.

**Comment by vincecima** [comment]
@Frost :+1:
