### ISSUE TITLE
How to update existing folder

### ISSUE THREAD

**Issue by golovan** [thoughtbot/rcm#206]
Hi guys!

I have a question about how to renew my files in .dotfiles dir.

Example: I have an Atom editor and have already created linked folder with 'mkrc .atom' and used it on another computer. Then later I added some packages to editor and want to renew my .dotfiles/atom folder. What should I do? 'rcup atom' seems not to add new files. If I try to run 'mkrc .atom' it creates folder .dotfiles/atom/.atom for some reason.

What I am doing wrong here and what is the best practice to deal with such cases.

And still I'm here could you confirm it takes a lot of time to update large amount of files like in my case. Several hours I believe. Mac 10, latest version.

Sorry for dummy questions, new to this tool. :)

**Comment by mike-burns** [comment]
To sync files, I recommend just `rcup`. You can get more verbosity and visibility into what it's doing by passing `-v`, like so: `rcup -v`.

Hours? That's exciting. How many files are we talking here?

**Comment by nisanth074** [comment]
I ran into this issue as well.

I had backed my configuration files by running `mkrc -C` commands many months ago. I bought a new laptop this week and wanted to use my configuration files on the new laptop. Since I changed my configuration files many times since the first backup, I tried backing them up again. Unfortunately, I couldn't find an easy way to do it. It seems like the only way to backup files again is to re-run individual `mkrc -C` commands.

For now, I wrote this [ruby script](https://gist.github.com/nisanth074/cc859d7fdd9e09473362d9d442f74afd)
to avoid the hassle of re-running individual `mkrc -C` commands. It'd be great if rcm can provide a way to backup configuration files it already tracks.

**Comment by nasr18** [comment]
Hi all,
I need one plugin `surround.vim`. Where I have to add this plugin?
under `~/.dotfiles/vim/plugin` or `~/.vim/plugin`?

**Comment by mike-burns** [comment]
@nisanth074 do you need to use `-C`? I'm not entirely sure how to solve that issue.

**Comment by mike-burns** [comment]
@nasr18 Add it under `~/.vim/plugin` then use `mkrc ~/.vim/plugin/surround.vim` to link it using rcm.

Please let me know how we can improve the docs to make this more clear.

**Comment by mat-m** [comment]
Suggestion:
* Add a block _"Add new files"_, saying to install them normally, then running mkrc over them.
* Add a Note, where folder contents are updated if the contents or one of the path elements were symlinked to a new target parent. 
* `-C` option is a copy, and we cannot update or contents below a copy
