### ISSUE TITLE
Debian install instructions no longer work for non-x86 systems

### ISSUE THREAD

**Issue by hairyhenderson** [thoughtbot/rcm#214]
Ever since https://github.com/thoughtbot/rcm/commit/f41e403fa8edbc3ba5bb893b60ad734f9e108660 was merged, the new instructions for installing `rcm` on Debian-based systems only work on `i386` and `amd64` architectures, despite the fact that none of the code is architecture-specific.

**Comment by hairyhenderson** [comment]
One note - it _is_ still possible to just download http://apt.thoughtbot.com/debian/pool/main/r/rcm/rcm_1.3.1-1_all.deb and install it with `dpkg`.

**Comment by mike-burns** [comment]
Ping @tabfugnic .

**Comment by tabfugnic** [comment]
Testing it now

**Comment by tabfugnic** [comment]
@hairyhenderson Reprepro, which i use for managing the apt server, no longer accepts an all architecture, it was a hack and was broken. I've instead added every officially supported Debian architecture to the apt server distribution file. This works on a RaspberryPi running on an ARM processor. Hopefully this helps

If not can you tell me what architecture you are on so that i might be able to fix it. Until then I'm closing this for now.

**Comment by hairyhenderson** [comment]
@tabfugnic Thank you! I can confirm that this works now. I've tested it on an `arm64` system too:

```
$ sudo apt-get install rcm
...
Get:1 http://apt.thoughtbot.com/debian stable/main arm64 rcm all 1.3.1-1 [19.9 kB]
...
Preparing to unpack .../archives/rcm_1.3.1-1_all.deb ...
...
```

👍
