### ISSUE TITLE
Doesn't work with directories

### ISSUE THREAD

**Issue by andrewhamon** [thoughtbot/rcm#225]
Okay, maybe I'm dumb, but here are some things I'm trying:

# Utterly broken: adding entire dotted directory
```bash
mkdir .my_config_dir
touch .my_config_dir/.my_config
mkrc .my_config_dir
cd .my_config_dir
-bash: cd: .my_config_dir: No such file or directory
# okay, thats weird....
rcup
cd .my_config_dir
-bash: cd: .my_config_dir: No such file or directory
# still gone
```

Expected outcome: The directory still exists (or is at least a symlink), with the files underneath also symlinked.
Actual outcome: The directory just disappears. Fortunately it exists under `~/.dotfiles` though.

# Mostly broken: adding entire not dotted directory
```bash
mkdir nodot_folder
touch nodot_folder/nodot_file
mkrc -U nodot_folder
cd nodot_folder/
# Yay, it works!
rm -r nodot_folder
rcup
cd nodot_folder
-bash: cd: nodot_folder: No such file or directory
# Oh....
cd .nodot_folder/
# Not the folder I wanted it to be
```

Expected outcome: The directory comes back without the dot

# And more
I'm having basically same set of issues when trying to add individual files under a directory rather than the entire directory

**Comment by mike-burns** [comment]
## Adding entire dotted directory

```
~% mkdir .foo
~% touch .foo/bar
~% mkrc .foo
~% ls -ld .foo
drwxrwxr-x 2 mike mike 4.0K Jul  6 11:42 .foo/
~% ls -l .foo
total 0
lrwxrwxrwx 1 mike mike 28 Jul  6 11:42 bar -> /home/mike/.dotfiles/foo/bar
~% rm -rf .foo ~/.dotfiles/foo
~% mkdir .foo
~% touch .foo/.bar
~% mkrc .foo
~% ls -ld .foo
/bin/ls: cannot access '.foo': No such file or directory
```

Interesting. So, that is a bug but also a bit of a special case. Do you have many dotted directories with dotted files under them? rcup(1) is not well-equipped to handle those.

## Adding entire not dotted directory

For the non-dotted directory, there's a bit of complexity here. `mkrc -U` will re-do that directory as a non-dotted, symlink'ed directory (like you say: yay, it works), but will not update your `.rcrc`. You must do that manually.

It might be useful to have a flag for mkrc(1) that will cause it to update your `.rcrc` based on the other flags, so e.g. `mkrc -rU nodot_dir` will add `UNDOTTED="nodot_dir $UNODTTED"` to `.rcrc`.

I hesitate to do this automatically every time because a good chunk of the rcm audience are people who are very particular about their rc files.

**Comment by andrewhamon** [comment]
> Do you have many dotted directories with dotted files under them?

At this point I can't remember if it was purely a contrived case or a legitimate problem I encountered. Perusing my dotfiles currently, I'm not finding any dotted files under dotted directories.

I ultimately decided to use gnu stow and never really pursued this any further.

Additionally, I'd like to apologize for my choice of language, particularly "Utterly broken", in retrospect it feels a bit rude. Thanks for responding and good luck with rcm :)

**Comment by mike-burns** [comment]
No prob, thanks for the update! I'm going to close this issue.
