### ISSUE TITLE
Repository no longer has a Release file

### ISSUE THREAD

**Issue by etiennebaque** [thoughtbot/rcm#245]
Under Debian, after adding the thoughtbot repository source (`echo "deb https://apt.thoughtbot.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/thoughtbot.list`), when doing a `sudo apt-get update` then, I get the following error:

```
E: The repository 'https://apt.thoughtbot.com/debian stable Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

About the Debian distro I use:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa
```

Could you please either fix the repository or update its url, whenever you get a chance?

**Comment by miguelfito** [comment]
Hi @etiennebaque!

The root cause of this issue seems to be related to `apt.thoughtbot.com` certificate expiration the last 26th May:

```bash
$ echo | openssl s_client -servername apt.thoughtbot.com -connect apt.thoughtbot.com:443 2>/dev/null | openssl x509 -noout -dates 
notBefore=Feb 25 23:41:55 2019 GMT
notAfter=May 26 23:41:55 2019 GMT
```

You can workaround this problem by now using the following command: 

```bash
$ sudo apt update -o Acquire::https::apt.thoughtbot.com::Verify-Peer=false && sudo apt list --upgradable
```

Hope **thoughtbot** fix this as soon as possible...

**Comment by etiennebaque** [comment]
@miguelfito Thanks very much for your answer, I'll give this a try as soon as possible.

**Comment by boneskull** [comment]
If anyone needs to add the key, this worked for me:

```shell
$ curl -kL https://apt.thoughtbot.com/thoughtbot.gpg.key | sudo apt-key add -
```

**Comment by develop7** [comment]
@boneskull you might find `apt-key adv --fetch-keys https://apt.thoughtbot.com/thoughtbot.gpg.key` more handy

**Comment by boneskull** [comment]
also note that `-o Acquire::https::apt.thoughtbot.com::Verify-Peer=false` works with an `upgrade` or `dist-upgrade` operation too

**Comment by bramswenson** [comment]
Just so we're all clear, this problem is not related to the gpg signing key. The root cause of this issue is an expired SSL certificate at the host apt.thoughtbot.com. It's kind of surprising that 16 days later no one has figured this out or taken the time to resolve it. I might be useful move this SSL cert to one of the ACME providers to prevent this in the future. There are many ways to ensure this basically never happens again.

As a long time `rcm` user I can say this isn't the first year we've dealt with thoughtbot ssl issues :( I do appreciate the great tool, so not the end of the world. Just a consistent annoyance. Thanks for all the hard work otherwise. Hopefully this can be resolved soon and with some level of permanence.

**Comment by bramswenson** [comment]
@mike-burns Any chance you could nudge the thoughtbot ops folks in charge of the `apt.thoughtbot.com` host? Thanks in advance!

**Comment by mike-burns** [comment]
@bramswenson should be good now. Thank you for your patience!

**Comment by rohanliston** [comment]
I have the same issue, but with the Ubuntu PPA as opposed to the Debian deb. 

```
E: The repository 'http://ppa.launchpad.net/martin-frost/thoughtbot-rcm/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

Should I open a separate issue for this?

**Comment by mike-burns** [comment]
Lemme ping @Frost -- people are having issues with the Ubuntu PPA. Thoughts?

**Comment by Frost** [comment]
@mike-burns That error message seems like it's trying to download the repo for Ubuntu 19.04 (Disco Dingo), and the reason it's failing is likely because I have forgotten to upload a package for that Ubuntu release.

It seems like having recurring to-do items that you have to perform once every 6 months is harder than I thought. I'll get to it during this week.

**Comment by Frost** [comment]
@rohanliston It seems as if rcm now (as of 19.04) exists in the Ubuntu "universe" package repo: https://packages.ubuntu.com/disco/rcm

As far as I can tell, my ppa stopped working with 19.04 because I hadn't uploaded a package for 19.04 (disco dingo).

I have done that now, but if there already exists a package in the universe repo I don't see any good reason why to keep uploading versions to new releases on my PPA.

You should be able to install rcm on Ubuntu 19.04 (and hopefully future releases) by just doing `apt update && apt install rcm` on a freshly installed system :)

**Comment by rohanliston** [comment]
@Frost Fantastic, thanks!

**Comment by todeveni** [comment]
In another news.
Your PGP key for apt.thoughtbot.com (debian) repository has expired yesterday. `EXPKEYSIG EC478DAB713A4BC3`
Ping @mike-burns

**Comment by maxkerp** [comment]
I'm still on Ubuntu 16.04 and getting this error recently

```
Reading package lists... Done
W: GPG error: https://apt.thoughtbot.com/debian stable InRelease: The following signatures were invalid: KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 0  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459  KEYEXPIRED 1571249459
W: The repository 'https://apt.thoughtbot.com/debian stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Is it me or does anybody else get this, too?

**Comment by Frost** [comment]
@maxkerp It looks as if you are trying to use the "Debian-based" installation instructions from the README. That is totally understandable, since Ubuntu is indeed Debian-based.

There are specific installation instructions for Ubuntu however, but they are unfortunately a bit further down in the README. For your convenience, I'll just copy-paste them here as well:

```bash
sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm
sudo apt-get update
sudo apt-get install rcm
```

I just verified this on a bare docker image with Ubuntu 16.04, and they almost worked out of the box. I first had to run `apt-get install software-properties-common` in order to get the `add-apt-repository` executable.

As I mentioned in [my earlier comment on this issue](https://github.com/thoughtbot/rcm/issues/245#issuecomment-513901388), `rcm` is now available in the `universe` package repo for Ubuntu 19.04 and newer versions. See #247 for more info on this.

**Comment by maxkerp** [comment]
Ohh :sweat_smile:

The ppa was already added. For some reason I also added the `thoughtbot.list` file from the `debian` install instructions.. I don't know why :see_no_evil: 

After deleting  `/etc/apt/sources.list.d/thoughtbot.list` everything works fine.

Thank you so much for your quick response and of course for `rcm` in general. It really helped me to get my dotfiles on the next level :heart:

**Comment by albertuscrs** [comment]
I was just doing `sudo apt update`  on elementary OS 5 Juno that built on Ubuntu 18.04.2 LTS   and I got this

```sh
Hit:1 https://download.mono-project.com/repo/ubuntu stable-bionic InRelease
Hit:2 https://dl.yarnpkg.com/debian stable InRelease                                                     
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                                             
Hit:4 http://dl.google.com/linux/chrome/deb stable Release                                               
Hit:5 http://packages.elementary.io/appcenter bionic InRelease                                           
Hit:7 http://id.archive.ubuntu.com/ubuntu bionic InRelease                                               
Hit:9 http://security.ubuntu.com/ubuntu bionic-security InRelease                                        
Hit:10 http://id.archive.ubuntu.com/ubuntu bionic-updates InRelease                                      
Hit:11 http://id.archive.ubuntu.com/ubuntu bionic-backports InRelease                                    
Get:6 https://apt.thoughtbot.com/debian stable InRelease [7.271 B]        
Hit:12 http://ppa.launchpad.net/dawidd0811/neofetch/ubuntu bionic InRelease      
Err:6 https://apt.thoughtbot.com/debian stable InRelease
  The following signatures were invalid: EXPKEYSIG EC478DAB713A4BC3 thoughtbot Security Team <security@thoughtbot.com>
Hit:13 http://ppa.launchpad.net/elementary-os/stable/ubuntu bionic InRelease   
Hit:14 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease           
Hit:15 http://ppa.launchpad.net/linrunner/tlp/ubuntu bionic InRelease          
Hit:16 http://ppa.launchpad.net/maarten-baert/simplescreenrecorder/ubuntu bionic InRelease
Hit:17 http://ppa.launchpad.net/martin-frost/thoughtbot-rcm/ubuntu bionic InRelease
Hit:18 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu bionic InRelease
Hit:19 http://ppa.launchpad.net/philip.scott/elementary-tweaks/ubuntu bionic InRelease
Hit:20 http://ppa.launchpad.net/shevchuk/dnscrypt-proxy/ubuntu bionic InRelease
Hit:21 http://ppa.launchpad.net/sylvain-pineau/kazam/ubuntu bionic InRelease   
Hit:22 http://ppa.launchpad.net/teejee2008/ppa/ubuntu bionic InRelease         
Hit:23 http://ppa.launchpad.net/ubuntuhandbook1/apps/ubuntu bionic InRelease   
Hit:24 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease       
Reading package lists... Done 
W: GPG error: https://apt.thoughtbot.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG EC478DAB713A4BC3 thoughtbot Security Team <security@thoughtbot.com>
E: The repository 'http://apt.thoughtbot.com/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

And then I was doing add GPG key using solution from @develop7 and got this 

```sh
▶ apt-key adv --fetch-keys https://apt.thoughtbot.com/thoughtbot.gpg.key
Executing: /tmp/apt-key-gpghome.hvs5IhvbxG/gpg.1.sh --fetch-keys https://apt.thoughtbot.com/thoughtbot.gpg.key
gpg: requesting key from 'https://apt.thoughtbot.com/thoughtbot.gpg.key'
gpg: key 84D7308EBE7FEF18: 8 signatures not checked due to missing keys
gpg: key 84D7308EBE7FEF18: "thoughtbot Security Team <security@thoughtbot.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

should I open new  issue for this? Thank you!

**Comment by maxkerp** [comment]
I suspect it's the same problem I had, but I'm not an expert on this. You added the debian source, but what you need is the the ubuntu ppa. 

```
W: GPG error: https://apt.thoughtbot.com/debian stable InRelease: The following...
```

I don't know why, but apparently ubuntu and debian handle signed repositories differently. Getting rid of the `sources.list.d` entry and adding the correct ppa should fix this.

Delete the following file and then follow @Frost instructions from this [comment](https://github.com/thoughtbot/rcm/issues/245#issuecomment-544284410)

```
rm /etc/apt/sources.list.d/thoughtbot.list
```

**Comment by albertuscrs** [comment]
it is good to go thank you @maxkerp !

**Comment by mike-burns** [comment]
Updated the README to make it clear that Ubuntu users should use the Ubuntu installation instructions. Thanks to @Frost for that.

**Comment by rupurt** [comment]
Heyo,

It looks like this is a problem again for Ubuntu 20.04 LTS (Focal Fossa) and needs to be uploaded.

Cheers for the great tool!
