### ISSUE TITLE
PGP signed configuration files

### ISSUE THREAD

**Issue by mike-burns** [thoughtbot/rcm#45]
The craziest of crazy ideas: if the repo contains a PGP signature, it will be verified before sync'ing the config files.

Relatedly crazy idea: check the signature of the `.rcrc` file.

**Comment by calebthompson** [comment]
This seems useful to me, but more as a personal verification. If I know that my key signed the config files and I can validate the signature, then I know that the config files are as I left them.

This is particularly useful when setting up a new machine, since I know that past me as approved these dotfiles and they've not been modified.

**Comment by mike-burns** [comment]
If I find this useful in the future, I'll open a PR about it. Thanks for the feedback, Team RCM.
